export const COUNTRIES = {
  ad: {
    original: 'Andorra',
    name: '안도라',
    capital: '안도라라베야',
    flag: 'https://flagcdn.com/w640/ad.png',
  },
  ae: {
    original: 'United Arab Emirates',
    name: '아랍에미리트',
    capital: '아부다비',
    flag: 'https://flagcdn.com/w640/ae.png',
  },
  af: {
    original: 'Afghanistan',
    name: '아프가니스탄',
    capital: '카불',
    flag: 'https://flagcdn.com/w640/af.png',
  },
  ag: {
    original: 'Antigua and Barbuda',
    name: '앤티가 바부다',
    capital: '세인트존스',
    flag: 'https://flagcdn.com/w640/ag.png',
  },
  ai: {
    original: 'Anguilla',
    name: '앵귈라',
    capital: '더밸리',
    flag: 'https://flagcdn.com/w640/ai.png',
  },
  al: {
    original: 'Albania',
    name: '알바니아',
    capital: '티라나',
    flag: 'https://flagcdn.com/w640/al.png',
  },
  am: {
    original: 'Armenia',
    name: '아르메니아',
    capital: '예레반',
    flag: 'https://flagcdn.com/w640/am.png',
  },
  ao: {
    original: 'Angola',
    name: '앙골라',
    capital: '루안다',
    flag: 'https://flagcdn.com/w640/ao.png',
  },
  aq: {
    original: 'Antarctica',
    name: '남극',
    capital: '-',
    flag: 'https://flagcdn.com/w640/aq.png',
  },
  ar: {
    original: 'Argentina',
    name: '아르헨티나',
    capital: '부에노스아이레스',
    flag: 'https://flagcdn.com/w640/ar.png',
  },
  as: {
    original: 'American Samoa',
    name: '아메리칸사모아',
    capital: '파고파고',
    flag: 'https://flagcdn.com/w640/as.png',
  },
  at: {
    original: 'Austria',
    name: '오스트리아',
    capital: '빈',
    flag: 'https://flagcdn.com/w640/at.png',
  },
  au: {
    original: 'Australia',
    name: '호주',
    capital: '캔버라',
    flag: 'https://flagcdn.com/w640/au.png',
  },
  aw: {
    original: 'Aruba',
    name: '아루바',
    capital: '오란예스타드',
    flag: 'https://flagcdn.com/w640/aw.png',
  },
  ax: {
    original: 'Åland Islands',
    name: '올란드 제도',
    capital: '마리에함',
    flag: 'https://flagcdn.com/w640/ax.png',
  },
  az: {
    original: 'Azerbaijan',
    name: '아제르바이잔',
    capital: '바쿠',
    flag: 'https://flagcdn.com/w640/az.png',
  },
  ba: {
    original: 'Bosnia and Herzegovina',
    name: '보스니아 헤르체고비나',
    capital: '사라예보',
    flag: 'https://flagcdn.com/w640/ba.png',
  },
  bb: {
    original: 'Barbados',
    name: '바베이도스',
    capital: '브리지타운',
    flag: 'https://flagcdn.com/w640/bb.png',
  },
  bd: {
    original: 'Bangladesh',
    name: '방글라데시',
    capital: '다카',
    flag: 'https://flagcdn.com/w640/bd.png',
  },
  be: {
    original: 'Belgium',
    name: '벨기에',
    capital: '브뤼셀',
    flag: 'https://flagcdn.com/w640/be.png',
  },
  bf: {
    original: 'Burkina Faso',
    name: '부르키나파소',
    capital: '와가두구',
    flag: 'https://flagcdn.com/w640/bf.png',
  },
  bg: {
    original: 'Bulgaria',
    name: '불가리아',
    capital: '소피아',
    flag: 'https://flagcdn.com/w640/bg.png',
  },
  bh: {
    original: 'Bahrain',
    name: '바레인',
    capital: '마나마',
    flag: 'https://flagcdn.com/w640/bh.png',
  },
  bi: {
    original: 'Burundi',
    name: '부룬디',
    capital: '기테가',
    flag: 'https://flagcdn.com/w640/bi.png',
  },
  bj: {
    original: 'Benin',
    name: '베냉',
    capital: '포르토노보',
    flag: 'https://flagcdn.com/w640/bj.png',
  },
  bl: {
    original: 'Saint Barthélemy',
    name: '생바르텔레미',
    capital: '구스타비아',
    flag: 'https://flagcdn.com/w640/bl.png',
  },
  bm: {
    original: 'Bermuda',
    name: '버뮤다',
    capital: '해밀턴',
    flag: 'https://flagcdn.com/w640/bm.png',
  },
  bn: {
    original: 'Brunei',
    name: '브루나이',
    capital: '반다르스리브가완',
    flag: 'https://flagcdn.com/w640/bn.png',
  },
  bo: {
    original: 'Bolivia',
    name: '볼리비아',
    capital: '라파스',
    flag: 'https://flagcdn.com/w640/bo.png',
  },
  bq: {
    original: 'Caribbean Netherlands',
    name: '카리브 네덜란드',
    capital: '-',
    flag: 'https://flagcdn.com/w640/bq.png',
  },
  br: {
    original: 'Brazil',
    name: '브라질',
    capital: '브라질리아',
    flag: 'https://flagcdn.com/w640/br.png',
  },
  bs: {
    original: 'Bahamas',
    name: '바하마',
    capital: '나소',
    flag: 'https://flagcdn.com/w640/bs.png',
  },
  bt: {
    original: 'Bhutan',
    name: '부탄',
    capital: '팀푸',
    flag: 'https://flagcdn.com/w640/bt.png',
  },
  bv: {
    original: 'Bouvet Island',
    name: '부베섬',
    capital: '-',
    flag: 'https://flagcdn.com/w640/bv.png',
  },
  bw: {
    original: 'Botswana',
    name: '보츠와나',
    capital: '가보로네',
    flag: 'https://flagcdn.com/w640/bw.png',
  },
  by: {
    original: 'Belarus',
    name: '벨라루스',
    capital: '민스크',
    flag: 'https://flagcdn.com/w640/by.png',
  },
  bz: {
    original: 'Belize',
    name: '벨리즈',
    capital: '벨모판',
    flag: 'https://flagcdn.com/w640/bz.png',
  },
  ca: {
    original: 'Canada',
    name: '캐나다',
    capital: '오타와',
    flag: 'https://flagcdn.com/w640/ca.png',
  },
  cc: {
    original: 'Cocos (Keeling) Islands',
    name: '코코스 제도',
    capital: '웨스트아일랜드',
    flag: 'https://flagcdn.com/w640/cc.png',
  },
  cd: {
    original: 'DR Congo',
    name: '콩고 민주 공화국',
    capital: '킨샤사',
    flag: 'https://flagcdn.com/w640/cd.png',
  },
  cf: {
    original: 'Central African Republic',
    name: '중앙아프리카 공화국',
    capital: '방기',
    flag: 'https://flagcdn.com/w640/cf.png',
  },
  cg: {
    original: 'Republic of the Congo',
    name: '콩고 공화국',
    capital: '브라자빌',
    flag: 'https://flagcdn.com/w640/cg.png',
  },
  ch: {
    original: 'Switzerland',
    name: '스위스',
    capital: '베른',
    flag: 'https://flagcdn.com/w640/ch.png',
  },
  ci: {
    original: "Côte d'Ivoire (Ivory Coast)",
    name: '코트디부아르',
    capital: '야무수크로',
    flag: 'https://flagcdn.com/w640/ci.png',
  },
  ck: {
    original: 'Cook Islands',
    name: '쿡 제도',
    capital: '아바루아',
    flag: 'https://flagcdn.com/w640/ck.png',
  },
  cl: {
    original: 'Chile',
    name: '칠레',
    capital: '산티아고',
    flag: 'https://flagcdn.com/w640/cl.png',
  },
  cm: {
    original: 'Cameroon',
    name: '카메룬',
    capital: '야운데',
    flag: 'https://flagcdn.com/w640/cm.png',
  },
  cn: {
    original: 'China',
    name: '중국',
    capital: '베이징',
    flag: 'https://flagcdn.com/w640/cn.png',
  },
  co: {
    original: 'Colombia',
    name: '콜롬비아',
    capital: '보고타',
    flag: 'https://flagcdn.com/w640/co.png',
  },
  cr: {
    original: 'Costa Rica',
    name: '코스타리카',
    capital: '산호세',
    flag: 'https://flagcdn.com/w640/cr.png',
  },
  cu: {
    original: 'Cuba',
    name: '쿠바',
    capital: '아바나',
    flag: 'https://flagcdn.com/w640/cu.png',
  },
  cv: {
    original: 'Cape Verde',
    name: '카보베르데',
    capital: '프라이아',
    flag: 'https://flagcdn.com/w640/cv.png',
  },
  cw: {
    original: 'Curaçao',
    name: '퀴라소',
    capital: '빌렘스타드',
    flag: 'https://flagcdn.com/w640/cw.png',
  },
  cx: {
    original: 'Christmas Island',
    name: '크리스마스섬',
    capital: '플라잉 피시 코브',
    flag: 'https://flagcdn.com/w640/cx.png',
  },
  cy: {
    original: 'Cyprus',
    name: '키프로스',
    capital: '니코시아',
    flag: 'https://flagcdn.com/w640/cy.png',
  },
  cz: {
    original: 'Czechia',
    name: '체코',
    capital: '프라하',
    flag: 'https://flagcdn.com/w640/cz.png',
  },
  de: {
    original: 'Germany',
    name: '독일',
    capital: '베를린',
    flag: 'https://flagcdn.com/w640/de.png',
  },
  dj: {
    original: 'Djibouti',
    name: '지부티',
    capital: '지부티',
    flag: 'https://flagcdn.com/w640/dj.png',
  },
  dk: {
    original: 'Denmark',
    name: '덴마크',
    capital: '코펜하겐',
    flag: 'https://flagcdn.com/w640/dk.png',
  },
  dm: {
    original: 'Dominica',
    name: '도미니카',
    capital: '로조',
    flag: 'https://flagcdn.com/w640/dm.png',
  },
  do: {
    original: 'Dominican Republic',
    name: '도미니카 공화국',
    capital: '산토도밍고',
    flag: 'https://flagcdn.com/w640/do.png',
  },
  dz: {
    original: 'Algeria',
    name: '알제리',
    capital: '알제',
    flag: 'https://flagcdn.com/w640/dz.png',
  },
  ec: {
    original: 'Ecuador',
    name: '에콰도르',
    capital: '키토',
    flag: 'https://flagcdn.com/w640/ec.png',
  },
  ee: {
    original: 'Estonia',
    name: '에스토니아',
    capital: '탈린',
    flag: 'https://flagcdn.com/w640/ee.png',
  },
  eg: {
    original: 'Egypt',
    name: '이집트',
    capital: '카이로',
    flag: 'https://flagcdn.com/w640/eg.png',
  },
  eh: {
    original: 'Western Sahara',
    name: '서사하라',
    capital: '엘아이운',
    flag: 'https://flagcdn.com/w640/eh.png',
  },
  er: {
    original: 'Eritrea',
    name: '에리트레아',
    capital: '아스마라',
    flag: 'https://flagcdn.com/w640/er.png',
  },
  es: {
    original: 'Spain',
    name: '스페인',
    capital: '마드리드',
    flag: 'https://flagcdn.com/w640/es.png',
  },
  et: {
    original: 'Ethiopia',
    name: '에티오피아',
    capital: '아디스아바바',
    flag: 'https://flagcdn.com/w640/et.png',
  },
  fi: {
    original: 'Finland',
    name: '핀란드',
    capital: '헬싱키',
    flag: 'https://flagcdn.com/w640/fi.png',
  },
  fj: {
    original: 'Fiji',
    name: '피지',
    capital: '수바',
    flag: 'https://flagcdn.com/w640/fj.png',
  },
  fk: {
    original: 'Falkland Islands',
    name: '포클랜드 제도',
    capital: '스탠리',
    flag: 'https://flagcdn.com/w640/fk.png',
  },
  fm: {
    original: 'Micronesia',
    name: '미크로네시아',
    capital: '팔리키르',
    flag: 'https://flagcdn.com/w640/fm.png',
  },
  fo: {
    original: 'Faroe Islands',
    name: '페로 제도',
    capital: '토르스하운',
    flag: 'https://flagcdn.com/w640/fo.png',
  },
  fr: {
    original: 'France',
    name: '프랑스',
    capital: '파리',
    flag: 'https://flagcdn.com/w640/fr.png',
  },
  ga: {
    original: 'Gabon',
    name: '가봉',
    capital: '리브르빌',
    flag: 'https://flagcdn.com/w640/ga.png',
  },
  gb: {
    original: 'United Kingdom',
    name: '영국',
    capital: '런던',
    flag: 'https://flagcdn.com/w640/gb.png',
  },
  gd: {
    original: 'Grenada',
    name: '그레나다',
    capital: '세인트조지스',
    flag: 'https://flagcdn.com/w640/gd.png',
  },
  ge: {
    original: 'Georgia',
    name: '조지아',
    capital: '트빌리시',
    flag: 'https://flagcdn.com/w640/ge.png',
  },
  gf: {
    original: 'French Guiana',
    name: '프랑스령 기아나',
    capital: '카옌',
    flag: 'https://flagcdn.com/w640/gf.png',
  },
  gg: {
    original: 'Guernsey',
    name: '건지',
    capital: '세인트피터포트',
    flag: 'https://flagcdn.com/w640/gg.png',
  },
  gh: {
    original: 'Ghana',
    name: '가나',
    capital: '아크라',
    flag: 'https://flagcdn.com/w640/gh.png',
  },
  gi: {
    original: 'Gibraltar',
    name: '지브롤터',
    capital: '지브롤터',
    flag: 'https://flagcdn.com/w640/gi.png',
  },
  gl: {
    original: 'Greenland',
    name: '그린란드',
    capital: '누크',
    flag: 'https://flagcdn.com/w640/gl.png',
  },
  gm: {
    original: 'Gambia',
    name: '감비아',
    capital: '반줄',
    flag: 'https://flagcdn.com/w640/gm.png',
  },
  gn: {
    original: 'Guinea',
    name: '기니',
    capital: '코나크리',
    flag: 'https://flagcdn.com/w640/gn.png',
  },
  gp: {
    original: 'Guadeloupe',
    name: '과들루프',
    capital: '바스테르',
    flag: 'https://flagcdn.com/w640/gp.png',
  },
  gq: {
    original: 'Equatorial Guinea',
    name: '적도 기니',
    capital: '말라보',
    flag: 'https://flagcdn.com/w640/gq.png',
  },
  gr: {
    original: 'Greece',
    name: '그리스',
    capital: '아테네',
    flag: 'https://flagcdn.com/w640/gr.png',
  },
  gt: {
    original: 'Guatemala',
    name: '과테말라',
    capital: '과테말라시티',
    flag: 'https://flagcdn.com/w640/gt.png',
  },
  gu: {
    original: 'Guam',
    name: '괌',
    capital: '하갓냐',
    flag: 'https://flagcdn.com/w640/gu.png',
  },
  gw: {
    original: 'Guinea-Bissau',
    name: '기니비사우',
    capital: '비사우',
    flag: 'https://flagcdn.com/w640/gw.png',
  },
  gy: {
    original: 'Guyana',
    name: '가이아나',
    capital: '조지타운',
    flag: 'https://flagcdn.com/w640/gy.png',
  },
  hk: {
    original: 'Hong Kong',
    name: '홍콩',
    capital: '-',
    flag: 'https://flagcdn.com/w640/hk.png',
  },
  hn: {
    original: 'Honduras',
    name: '온두라스',
    capital: '테구시갈파',
    flag: 'https://flagcdn.com/w640/hn.png',
  },
  hr: {
    original: 'Croatia',
    name: '크로아티아',
    capital: '자그레브',
    flag: 'https://flagcdn.com/w640/hr.png',
  },
  ht: {
    original: 'Haiti',
    name: '아이티',
    capital: '포르토프랭스',
    flag: 'https://flagcdn.com/w640/ht.png',
  },
  hu: {
    original: 'Hungary',
    name: '헝가리',
    capital: '부다페스트',
    flag: 'https://flagcdn.com/w640/hu.png',
  },
  id: {
    original: 'Indonesia',
    name: '인도네시아',
    capital: '자카르타',
    flag: 'https://flagcdn.com/w640/id.png',
  },
  ie: {
    original: 'Ireland',
    name: '아일랜드',
    capital: '더블린',
    flag: 'https://flagcdn.com/w640/ie.png',
  },
  il: {
    original: 'Israel',
    name: '이스라엘',
    capital: '예루살렘',
    flag: 'https://flagcdn.com/w640/il.png',
  },
  im: {
    original: 'Isle of Man',
    name: '맨섬',
    capital: '더글러스',
    flag: 'https://flagcdn.com/w640/im.png',
  },
  in: {
    original: 'India',
    name: '인도',
    capital: '뉴델리',
    flag: 'https://flagcdn.com/w640/in.png',
  },
  io: {
    original: 'British Indian Ocean Territory',
    name: '영국령 인도양 지역',
    capital: '-',
    flag: 'https://flagcdn.com/w640/io.png',
  },
  iq: {
    original: 'Iraq',
    name: '이라크',
    capital: '바그다드',
    flag: 'https://flagcdn.com/w640/iq.png',
  },
  ir: {
    original: 'Iran',
    name: '이란',
    capital: '테헤란',
    flag: 'https://flagcdn.com/w640/ir.png',
  },
  is: {
    original: 'Iceland',
    name: '아이슬란드',
    capital: '레이캬비크',
    flag: 'https://flagcdn.com/w640/is.png',
  },
  it: {
    original: 'Italy',
    name: '이탈리아',
    capital: '로마',
    flag: 'https://flagcdn.com/w640/it.png',
  },
  je: {
    original: 'Jersey',
    name: '저지',
    capital: '세인트헬리어',
    flag: 'https://flagcdn.com/w640/je.png',
  },
  jm: {
    original: 'Jamaica',
    name: '자메이카',
    capital: '킹스턴',
    flag: 'https://flagcdn.com/w640/jm.png',
  },
  jo: {
    original: 'Jordan',
    name: '요르단',
    capital: '암만',
    flag: 'https://flagcdn.com/w640/jo.png',
  },
  jp: {
    original: 'Japan',
    name: '일본',
    capital: '도쿄',
    flag: 'https://flagcdn.com/w640/jp.png',
  },
  ke: {
    original: 'Kenya',
    name: '케냐',
    capital: '나이로비',
    flag: 'https://flagcdn.com/w640/ke.png',
  },
  kg: {
    original: 'Kyrgyzstan',
    name: '키르기스스탄',
    capital: '비슈케크',
    flag: 'https://flagcdn.com/w640/kg.png',
  },
  kh: {
    original: 'Cambodia',
    name: '캄보디아',
    capital: '프놈펜',
    flag: 'https://flagcdn.com/w640/kh.png',
  },
  ki: {
    original: 'Kiribati',
    name: '키리바시',
    capital: '타라와',
    flag: 'https://flagcdn.com/w640/ki.png',
  },
  km: {
    original: 'Comoros',
    name: '코모로',
    capital: '모로니',
    flag: 'https://flagcdn.com/w640/km.png',
  },
  kn: {
    original: 'Saint Kitts and Nevis',
    name: '세인트키츠 네비스',
    capital: '바스테르',
    flag: 'https://flagcdn.com/w640/kn.png',
  },
  kp: {
    original: 'North Korea',
    name: '북한',
    capital: '평양',
    flag: 'https://flagcdn.com/w640/kp.png',
  },
  kr: {
    original: 'South Korea',
    name: '대한민국',
    capital: '서울',
    flag: 'https://flagcdn.com/w640/kr.png',
  },
  kw: {
    original: 'Kuwait',
    name: '쿠웨이트',
    capital: '쿠웨이트시티',
    flag: 'https://flagcdn.com/w640/kw.png',
  },
  ky: {
    original: 'Cayman Islands',
    name: '케이맨 제도',
    capital: '조지타운',
    flag: 'https://flagcdn.com/w640/ky.png',
  },
  kz: {
    original: 'Kazakhstan',
    name: '카자흐스탄',
    capital: '아스타나',
    flag: 'https://flagcdn.com/w640/kz.png',
  },
  la: {
    original: 'Laos',
    name: '라오스',
    capital: '비엔티안',
    flag: 'https://flagcdn.com/w640/la.png',
  },
  lb: {
    original: 'Lebanon',
    name: '레바논',
    capital: '베이루트',
    flag: 'https://flagcdn.com/w640/lb.png',
  },
  lc: {
    original: 'Saint Lucia',
    name: '세인트루시아',
    capital: '캐스트리스',
    flag: 'https://flagcdn.com/w640/lc.png',
  },
  li: {
    original: 'Liechtenstein',
    name: '리히텐슈타인',
    capital: '파두츠',
    flag: 'https://flagcdn.com/w640/li.png',
  },
  lk: {
    original: 'Sri Lanka',
    name: '스리랑카',
    capital: '스리자야와르데네푸라코테',
    flag: 'https://flagcdn.com/w640/lk.png',
  },
  lr: {
    original: 'Liberia',
    name: '라이베리아',
    capital: '몬로비아',
    flag: 'https://flagcdn.com/w640/lr.png',
  },
  ls: {
    original: 'Lesotho',
    name: '레소토',
    capital: '마세루',
    flag: 'https://flagcdn.com/w640/ls.png',
  },
  lt: {
    original: 'Lithuania',
    name: '리투아니아',
    capital: '빌뉴스',
    flag: 'https://flagcdn.com/w640/lt.png',
  },
  lu: {
    original: 'Luxembourg',
    name: '룩셈부르크',
    capital: '룩셈부르크',
    flag: 'https://flagcdn.com/w640/lu.png',
  },
  lv: {
    original: 'Latvia',
    name: '라트비아',
    capital: '리가',
    flag: 'https://flagcdn.com/w640/lv.png',
  },
  ly: {
    original: 'Libya',
    name: '리비아',
    capital: '트리폴리',
    flag: 'https://flagcdn.com/w640/ly.png',
  },
  ma: {
    original: 'Morocco',
    name: '모로코',
    capital: '라바트',
    flag: 'https://flagcdn.com/w640/ma.png',
  },
  mc: {
    original: 'Monaco',
    name: '모나코',
    capital: '모나코',
    flag: 'https://flagcdn.com/w640/mc.png',
  },
  md: {
    original: 'Moldova',
    name: '몰도바',
    capital: '키시너우',
    flag: 'https://flagcdn.com/w640/md.png',
  },
  me: {
    original: 'Montenegro',
    name: '몬테네그로',
    capital: '포드고리차',
    flag: 'https://flagcdn.com/w640/me.png',
  },
  mg: {
    original: 'Madagascar',
    name: '마다가스카르',
    capital: '안타나나리보',
    flag: 'https://flagcdn.com/w640/mg.png',
  },
  mh: {
    original: 'Marshall Islands',
    name: '마셜 제도',
    capital: '마주로',
    flag: 'https://flagcdn.com/w640/mh.png',
  },
  mk: {
    original: 'North Macedonia',
    name: '북마케도니아',
    capital: '스코페',
    flag: 'https://flagcdn.com/w640/mk.png',
  },
  ml: {
    original: 'Mali',
    name: '말리',
    capital: '바마코',
    flag: 'https://flagcdn.com/w640/ml.png',
  },
  mm: {
    original: 'Myanmar',
    name: '미얀마',
    capital: '네피도',
    flag: 'https://flagcdn.com/w640/mm.png',
  },
  mn: {
    original: 'Mongolia',
    name: '몽골',
    capital: '울란바토르',
    flag: 'https://flagcdn.com/w640/mn.png',
  },
  mo: {
    original: 'Macau',
    name: '마카오',
    capital: '-',
    flag: 'https://flagcdn.com/w640/mo.png',
  },
  mp: {
    original: 'Northern Mariana Islands',
    name: '북마리아나 제도',
    capital: '사이판',
    flag: 'https://flagcdn.com/w640/mp.png',
  },
  mq: {
    original: 'Martinique',
    name: '마르티니크',
    capital: '포르드프랑스',
    flag: 'https://flagcdn.com/w640/mq.png',
  },
  mr: {
    original: 'Mauritania',
    name: '모리타니',
    capital: '누악쇼트',
    flag: 'https://flagcdn.com/w640/mr.png',
  },
  ms: {
    original: 'Montserrat',
    name: '몬트세랫',
    capital: '플리머스',
    flag: 'https://flagcdn.com/w640/ms.png',
  },
  mt: {
    original: 'Malta',
    name: '몰타',
    capital: '발레타',
    flag: 'https://flagcdn.com/w640/mt.png',
  },
  mu: {
    original: 'Mauritius',
    name: '모리셔스',
    capital: '포트루이스',
    flag: 'https://flagcdn.com/w640/mu.png',
  },
  mv: {
    original: 'Maldives',
    name: '몰디브',
    capital: '말레',
    flag: 'https://flagcdn.com/w640/mv.png',
  },
  mw: {
    original: 'Malawi',
    name: '말라위',
    capital: '릴롱궤',
    flag: 'https://flagcdn.com/w640/mw.png',
  },
  mx: {
    original: 'Mexico',
    name: '멕시코',
    capital: '멕시코시티',
    flag: 'https://flagcdn.com/w640/mx.png',
  },
  my: {
    original: 'Malaysia',
    name: '말레이시아',
    capital: '쿠알라룸푸르',
    flag: 'https://flagcdn.com/w640/my.png',
  },
  mz: {
    original: 'Mozambique',
    name: '모잠비크',
    capital: '마푸투',
    flag: 'https://flagcdn.com/w640/mz.png',
  },
  na: {
    original: 'Namibia',
    name: '나미비아',
    capital: '빈트후크',
    flag: 'https://flagcdn.com/w640/na.png',
  },
  nc: {
    original: 'New Caledonia',
    name: '뉴칼레도니아',
    capital: '누메아',
    flag: 'https://flagcdn.com/w640/nc.png',
  },
  ne: {
    original: 'Niger',
    name: '니제르',
    capital: '니아메',
    flag: 'https://flagcdn.com/w640/ne.png',
  },
  nf: {
    original: 'Norfolk Island',
    name: '노퍽섬',
    capital: '킹스턴',
    flag: 'https://flagcdn.com/w640/nf.png',
  },
  ng: {
    original: 'Nigeria',
    name: '나이지리아',
    capital: '아부자',
    flag: 'https://flagcdn.com/w640/ng.png',
  },
  ni: {
    original: 'Nicaragua',
    name: '니카라과',
    capital: '마나과',
    flag: 'https://flagcdn.com/w640/ni.png',
  },
  nl: {
    original: 'Netherlands',
    name: '네덜란드',
    capital: '암스테르담',
    flag: 'https://flagcdn.com/w640/nl.png',
  },
  no: {
    original: 'Norway',
    name: '노르웨이',
    capital: '오슬로',
    flag: 'https://flagcdn.com/w640/no.png',
  },
  np: {
    original: 'Nepal',
    name: '네팔',
    capital: '카트만두',
    flag: 'https://flagcdn.com/w640/np.png',
  },
  nr: {
    original: 'Nauru',
    name: '나우루',
    capital: '야렌',
    flag: 'https://flagcdn.com/w640/nr.png',
  },
  nu: {
    original: 'Niue',
    name: '니우에',
    capital: '알로피',
    flag: 'https://flagcdn.com/w640/nu.png',
  },
  nz: {
    original: 'New Zealand',
    name: '뉴질랜드',
    capital: '웰링턴',
    flag: 'https://flagcdn.com/w640/nz.png',
  },
  om: {
    original: 'Oman',
    name: '오만',
    capital: '무스카트',
    flag: 'https://flagcdn.com/w640/om.png',
  },
  pa: {
    original: 'Panama',
    name: '파나마',
    capital: '파나마시티',
    flag: 'https://flagcdn.com/w640/pa.png',
  },
  pe: {
    original: 'Peru',
    name: '페루',
    capital: '리마',
    flag: 'https://flagcdn.com/w640/pe.png',
  },
  pf: {
    original: 'French Polynesia',
    name: '프랑스령 폴리네시아',
    capital: '파페에테',
    flag: 'https://flagcdn.com/w640/pf.png',
  },
  pg: {
    original: 'Papua New Guinea',
    name: '파푸아뉴기니',
    capital: '포트모르즈비',
    flag: 'https://flagcdn.com/w640/pg.png',
  },
  ph: {
    original: 'Philippines',
    name: '필리핀',
    capital: '마닐라',
    flag: 'https://flagcdn.com/w640/ph.png',
  },
  pk: {
    original: 'Pakistan',
    name: '파키스탄',
    capital: '이슬라마바드',
    flag: 'https://flagcdn.com/w640/pk.png',
  },
  pl: {
    original: 'Poland',
    name: '폴란드',
    capital: '바르샤바',
    flag: 'https://flagcdn.com/w640/pl.png',
  },
  pm: {
    original: 'Saint Pierre and Miquelon',
    name: '생피에르 미클롱',
    capital: '생피에르',
    flag: 'https://flagcdn.com/w640/pm.png',
  },
  pn: {
    original: 'Pitcairn Islands',
    name: '핏케언 제도',
    capital: '아담스타운',
    flag: 'https://flagcdn.com/w640/pn.png',
  },
  pr: {
    original: 'Puerto Rico',
    name: '푸에르토리코',
    capital: '산후안',
    flag: 'https://flagcdn.com/w640/pr.png',
  },
  ps: {
    original: 'Palestine',
    name: '팔레스타인',
    capital: '예루살렘',
    flag: 'https://flagcdn.com/w640/ps.png',
  },
  pt: {
    original: 'Portugal',
    name: '포르투갈',
    capital: '리스본',
    flag: 'https://flagcdn.com/w640/pt.png',
  },
  pw: {
    original: 'Palau',
    name: '팔라우',
    capital: '응게룰무드',
    flag: 'https://flagcdn.com/w640/pw.png',
  },
  py: {
    original: 'Paraguay',
    name: '파라과이',
    capital: '아순시온',
    flag: 'https://flagcdn.com/w640/py.png',
  },
  qa: {
    original: 'Qatar',
    name: '카타르',
    capital: '도하',
    flag: 'https://flagcdn.com/w640/qa.png',
  },
  re: {
    original: 'Réunion',
    name: '레위니옹',
    capital: '생드니',
    flag: 'https://flagcdn.com/w640/re.png',
  },
  ro: {
    original: 'Romania',
    name: '루마니아',
    capital: '부쿠레슈티',
    flag: 'https://flagcdn.com/w640/ro.png',
  },
  rs: {
    original: 'Serbia',
    name: '세르비아',
    capital: '베오그라드',
    flag: 'https://flagcdn.com/w640/rs.png',
  },
  ru: {
    original: 'Russia',
    name: '러시아',
    capital: '모스크바',
    flag: 'https://flagcdn.com/w640/ru.png',
  },
  rw: {
    original: 'Rwanda',
    name: '르완다',
    capital: '키갈리',
    flag: 'https://flagcdn.com/w640/rw.png',
  },
  sa: {
    original: 'Saudi Arabia',
    name: '사우디아라비아',
    capital: '리야드',
    flag: 'https://flagcdn.com/w640/sa.png',
  },
  sb: {
    original: 'Solomon Islands',
    name: '솔로몬 제도',
    capital: '호니아라',
    flag: 'https://flagcdn.com/w640/sb.png',
  },
  sc: {
    original: 'Seychelles',
    name: '세이셸',
    capital: '빅토리아',
    flag: 'https://flagcdn.com/w640/sc.png',
  },
  sd: {
    original: 'Sudan',
    name: '수단',
    capital: '하르툼',
    flag: 'https://flagcdn.com/w640/sd.png',
  },
  se: {
    original: 'Sweden',
    name: '스웨덴',
    capital: '스톡홀름',
    flag: 'https://flagcdn.com/w640/se.png',
  },
  sg: {
    original: 'Singapore',
    name: '싱가포르',
    capital: '싱가포르',
    flag: 'https://flagcdn.com/w640/sg.png',
  },
  si: {
    original: 'Slovenia',
    name: '슬로베니아',
    capital: '류블랴나',
    flag: 'https://flagcdn.com/w640/si.png',
  },
  sk: {
    original: 'Slovakia',
    name: '슬로바키아',
    capital: '브라티슬라바',
    flag: 'https://flagcdn.com/w640/sk.png',
  },
  sl: {
    original: 'Sierra Leone',
    name: '시에라리온',
    capital: '프리타운',
    flag: 'https://flagcdn.com/w640/sl.png',
  },
  sm: {
    original: 'San Marino',
    name: '산마리노',
    capital: '산마리노',
    flag: 'https://flagcdn.com/w640/sm.png',
  },
  sn: {
    original: 'Senegal',
    name: '세네갈',
    capital: '다카르',
    flag: 'https://flagcdn.com/w640/sn.png',
  },
  so: {
    original: 'Somalia',
    name: '소말리아',
    capital: '모가디슈',
    flag: 'https://flagcdn.com/w640/so.png',
  },
  sr: {
    original: 'Suriname',
    name: '수리남',
    capital: '파라마리보',
    flag: 'https://flagcdn.com/w640/sr.png',
  },
  ss: {
    original: 'South Sudan',
    name: '남수단',
    capital: '주바',
    flag: 'https://flagcdn.com/w640/ss.png',
  },
  st: {
    original: 'São Tomé and Príncipe',
    name: '상투메 프린시페',
    capital: '상투메',
    flag: 'https://flagcdn.com/w640/st.png',
  },
  sv: {
    original: 'El Salvador',
    name: '엘살바도르',
    capital: '산살바도르',
    flag: 'https://flagcdn.com/w640/sv.png',
  },
  sx: {
    original: 'Sint Maarten',
    name: '신트마르턴',
    capital: '필립스버그',
    flag: 'https://flagcdn.com/w640/sx.png',
  },
  sy: {
    original: 'Syria',
    name: '시리아',
    capital: '다마스쿠스',
    flag: 'https://flagcdn.com/w640/sy.png',
  },
  sz: {
    original: 'Eswatini',
    name: '에스와티니',
    capital: '음바바네',
    flag: 'https://flagcdn.com/w640/sz.png',
  },
  tc: {
    original: 'Turks and Caicos Islands',
    name: '터크스 케이커스 제도',
    capital: '코번트리',
    flag: 'https://flagcdn.com/w640/tc.png',
  },
  td: {
    original: 'Chad',
    name: '차드',
    capital: '은자메나',
    flag: 'https://flagcdn.com/w640/td.png',
  },
  tg: {
    original: 'Togo',
    name: '토고',
    capital: '로메',
    flag: 'https://flagcdn.com/w640/tg.png',
  },
  th: {
    original: 'Thailand',
    name: '태국',
    capital: '방콕',
    flag: 'https://flagcdn.com/w640/th.png',
  },
  tj: {
    original: 'Tajikistan',
    name: '타지키스탄',
    capital: '두샨베',
    flag: 'https://flagcdn.com/w640/tj.png',
  },
  tk: {
    original: 'Tokelau',
    name: '토켈라우',
    capital: '-',
    flag: 'https://flagcdn.com/w640/tk.png',
  },
  tl: {
    original: 'Timor-Leste',
    name: '동티모르',
    capital: '딜리',
    flag: 'https://flagcdn.com/w640/tl.png',
  },
  tm: {
    original: 'Turkmenistan',
    name: '투르크메니스탄',
    capital: '아슈하바트',
    flag: 'https://flagcdn.com/w640/tm.png',
  },
  tn: {
    original: 'Tunisia',
    name: '튀니지',
    capital: '튀니스',
    flag: 'https://flagcdn.com/w640/tn.png',
  },
  to: {
    original: 'Tonga',
    name: '통가',
    capital: '누쿠알로파',
    flag: 'https://flagcdn.com/w640/to.png',
  },
  tr: {
    original: 'Turkey',
    name: '터키',
    capital: '앙카라',
    flag: 'https://flagcdn.com/w640/tr.png',
  },
  tt: {
    original: 'Trinidad and Tobago',
    name: '트리니다드 토바고',
    capital: '포트오브스페인',
    flag: 'https://flagcdn.com/w640/tt.png',
  },
  tv: {
    original: 'Tuvalu',
    name: '투발루',
    capital: '푸나푸티',
    flag: 'https://flagcdn.com/w640/tv.png',
  },
  tw: {
    original: 'Taiwan',
    name: '대만',
    capital: '타이베이',
    flag: 'https://flagcdn.com/w640/tw.png',
  },
  tz: {
    original: 'Tanzania',
    name: '탄자니아',
    capital: '도도마',
    flag: 'https://flagcdn.com/w640/tz.png',
  },
  ua: {
    original: 'Ukraine',
    name: '우크라이나',
    capital: '키이우',
    flag: 'https://flagcdn.com/w640/ua.png',
  },
  ug: {
    original: 'Uganda',
    name: '우간다',
    capital: '캄팔라',
    flag: 'https://flagcdn.com/w640/ug.png',
  },
  us: {
    original: 'United States',
    name: '미국',
    capital: '워싱턴 D.C.',
    flag: 'https://flagcdn.com/w640/us.png',
  },
  uy: {
    original: 'Uruguay',
    name: '우루과이',
    capital: '몬테비데오',
    flag: 'https://flagcdn.com/w640/uy.png',
  },
  uz: {
    original: 'Uzbekistan',
    name: '우즈베키스탄',
    capital: '타슈켄트',
    flag: 'https://flagcdn.com/w640/uz.png',
  },
  va: {
    original: 'Vatican City',
    name: '바티칸 시국',
    capital: '바티칸 시국',
    flag: 'https://flagcdn.com/w640/va.png',
  },
  vc: {
    original: 'Saint Vincent and the Grenadines',
    name: '세인트빈센트 그레나딘',
    capital: '킹스타운',
    flag: 'https://flagcdn.com/w640/vc.png',
  },
  ve: {
    original: 'Venezuela',
    name: '베네수엘라',
    capital: '카라카스',
    flag: 'https://flagcdn.com/w640/ve.png',
  },
  vg: {
    original: 'British Virgin Islands',
    name: '영국령 버진아일랜드',
    capital: '로드타운',
    flag: 'https://flagcdn.com/w640/vg.png',
  },
  vi: {
    original: 'U.S. Virgin Islands',
    name: '미국령 버진아일랜드',
    capital: '샬롯어맬리',
    flag: 'https://flagcdn.com/w640/vi.png',
  },
  vn: {
    original: 'Vietnam',
    name: '베트남',
    capital: '하노이',
    flag: 'https://flagcdn.com/w640/vn.png',
  },
  vu: {
    original: 'Vanuatu',
    name: '바누아투',
    capital: '포트빌라',
    flag: 'https://flagcdn.com/w640/vu.png',
  },
  wf: {
    original: 'Wallis and Futuna',
    name: '왈리스 푸투나',
    capital: '마타우투',
    flag: 'https://flagcdn.com/w640/wf.png',
  },
  ws: {
    original: 'Samoa',
    name: '사모아',
    capital: '아피아',
    flag: 'https://flagcdn.com/w640/ws.png',
  },
  ye: {
    original: 'Yemen',
    name: '예멘',
    capital: '사나',
    flag: 'https://flagcdn.com/w640/ye.png',
  },
  za: {
    original: 'South Africa',
    name: '남아프리카 공화국',
    capital: '프리토리아',
    flag: 'https://flagcdn.com/w640/za.png',
  },
  zm: {
    original: 'Zambia',
    name: '잠비아',
    capital: '루사카',
    flag: 'https://flagcdn.com/w640/zm.png',
  },
  zw: {
    original: 'Zimbabwe',
    name: '짐바브웨',
    capital: '하라레',
    flag: 'https://flagcdn.com/w640/zw.png',
  },
};
